# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'English2Assistant' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # Pods for English2Assistant
  pod 'Alamofire', '~> 4.4'
  pod 'IBAnimatable'
  pod 'Kingfisher', '~> 3.10.1'
  pod 'SwiftyJSON', '~> 3.1.4'
  pod 'SnapKit', '~> 3.2.0'
end

